
# version: '2' is required for balenaOS v2.x releases
version: "2"

# we're going to create two services, one for the kiosk app and one for the chrome block that will display the kiosk app
services:
  kiosk-app:
    build: ./kiosk-app
    ports:
      - "80:80"
#   should use expose instead of ports when we don't need to map ports to host
#    expose:
#      - "80"

    restart: always     # restart the container if it exits
    network_mode: host  # use host network mode to make sure the container can access the internet


  chrome-block:
    image: bh.cr/balenalabs/browser-aarch64
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    ports:
        - '5011' # management API (optional)
        - '35173' # Chromium debugging port (optional)
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)
    restart: always
    
    environment:
      # refer to https://github.com/balena-labs-projects/browser#environment-variables for more information
      # LAUNCH_URL	http or https URL	N\A	Web page to display
      # DISPLAY_NUM	n	0	Display number to use
      # LOCAL_HTTP_DELAY	Number (seconds)	0	Number of seconds to wait for a local HTTP service to start before trying to detect it
      # KIOSK	0, 1	0	Run in kiosk mode with no menus or status bars. 0 = off, 1 = on
      # SHOW_CURSOR	0, 1	0	Enables/disables the cursor when in kiosk mode 0 = off, 1 = on
      # FLAGS	many!	N/A	Overrides the flags chromium is started with. Enter a space (' ') separated list of flags (e.g. --noerrdialogs --disable-session-crashed-bubble) Use with caution!
      # PERSISTENT	0, 1	0	Enables/disables user profile data being stored on the device. Note: you'll need to create a settings volume. See example above 0 = off, 1 = on
      # ROTATE_DISPLAY	normal, left, right, inverted	normal	Rotates the display
      # TOUCHSCREEN	string	N\A	Name of Touch Input to rotate
      # ENABLE_GPU	0, 1	0	Enables the GPU rendering. Necessary for Pi3B+ to display YouTube videos. 0 = off, 1 = on
      # WINDOW_SIZE	x,y	Detected screen resolution	Sets the browser window size, such as 800,600. Note: Reverse the dimensions if you also rotate the display to left or right
      # WINDOW_POSITION	x,y	0,0	Specifies the browser window position on the screen
      # API_PORT	port number	5011	Specifies the port number the API runs on
      # REMOTE_DEBUG_PORT	port number	35173	Specifies the port number the chrome remote debugger runs on
      - LAUNCH_URL=http://kiosk-app:80
      - DISPLAY_NUM=0
      - LOCAL_HTTP_DELAY=5
      - KIOSK=1
      - SHOW_CURSOR=0
      - PERSISTENT=0
      - ROTATE_DISPLAY=normal
      - ENABLE_GPU=1
      - WINDOW_SIZE=1920,1080
      - WINDOW_POSITION=0,0
      - API_PORT=5011
      - REMOTE_DEBUG_PORT=35173
      
